version: "3.3"

services:
  db:
    image: garage-db_mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - type: volume
        source: dbdata
        target: /data/db

  front_end:
    image: garage-site:latest
    build: ./site
    command: npm start
    container_name: front_end
    ports:
      - "81:3000"
    networks:
      - backend
    environment:
      - DEBUG=app:*

  back_end:
    image: garage-rest:latest
    build: ./rest
    command: npm start
    container_name: back_end
    ports:
      - "8081:3000"
    depends_on:
      - "db"
    networks:
      - backend
    environment:
      - DEBUG=app:*

networks:
  frontend:
  backend:

volumes:
  dbdata:
