version: "3.3"

services:
  db:
    image: garage-db_mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - type: volume
        source: dbdata
        target: /data/db

  front_end:
    image: garage-site:latest
    build: ./site
    command: npm start
    container_name: front_end
    ports:
      - "80:3000"
    networks:
      - backend
    environment:
      - DEBUG=app:*
    volumes:
      - ./site:/opt/app

  back_end:
    image: garage-rest:latest
    build: ./rest
    command: npm start
    container_name: back_end
    ports:
      - "8080:3000"
    networks:
      - backend
    environment:
      - DEBUG=app:*
    volumes:
      - ./rest:/opt/app

networks:
  frontend:
  backend:

volumes:
  dbdata:
