version: "3.3"

services:
  jenkins:
    image: garage-jenkins:latest
    build:
        context: ./jenkins
        dockerfile: dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
    networks:
      - isolated_garage
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
      #- /var/run/docker.sock:/var/run/docker.sock
  db:
    image: garage-db_mongo:latest
    build:
        context: ./db
        dockerfile: dockerfile
    container_name: db
    ports:
      - "27017:27017"
    networks:
      - isolated_garage
    volumes:
      - type: volume
        source: dbdata
        target: /data/db
  back_end:
    image: garage-rest:latest
    build:
        context: ./rest
        dockerfile: dockerfile
    command: npm start
    container_name: back_end
    ports:
      - "8081:3000"
    networks:
      - isolated_garage
    environment:
      - DEBUG=app:*
    volumes:
      - ./rest:/opt/app
  front_end:
    image: garage-site:latest
    build:
        context: ./site
        dockerfile: dockerfile
    command: npm start
    container_name: front_end
    ports:
      - "81:3000"
    networks:
      - isolated_garage
    environment:
      - DEBUG=app:*
    volumes:
      - ./site:/opt/app
volumes:
  dbdata:
  jenkins-data:
  jenkins-log:
networks:
  isolated_garage:
